# Generated by Django 3.1.3 on 2020-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Goods Name', max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('comment', models.TextField(help_text='Discribe the delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Goods Name', max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('comment', models.TextField(help_text='Discribe the Destination')),
            ],
        ),
    ]
