apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-3
  labels:
    app: django-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-3-container
  template:
    metadata:
      labels:
        app: django-3-container
    spec:
      containers:
        - name: django-3
          image: okayjosh/warehouse:latest
          command: ['/bin/bash', 'run.sh'] # runs migrations and starts the server
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-3-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-3-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-3-service
